### ISSUE TITLE
Make e2e tests on all possible environments

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/strapi-plugin-meilisearch#103]
As of today tests are only done on `strapi start` in `no-reload` mode. 
It would be better if we tried the following as well
- strapi develop
- strapi develope --admin-watch
- NODE_ENV=production strapi start

I tried adding this to the yaml file as it works locally but at the second tests it fails: 
```yaml
      - name: Test develop admin watch
        uses: cypress-io/github-action@v2
        with:
          build: yarn playground:build
          start: yarn playground:dev
          env: env=watch
      - name: Test develop soft watch
        uses: cypress-io/github-action@v2
        with:
          build: yarn playground:build
          start: yarn playground:dev
          env: env=develop
      - name: Test production
        uses: cypress-io/github-action@v2
        with:
          build: yarn playground:build
          start: yarn playground:dev
          env: env=ci
```

Maybe they just need to be separated in a different job each?
