### ISSUE TITLE
Doesn't start to index.

### ISSUE THREAD

**Issue by monkeydaichan** [meilisearch/strapi-plugin-meilisearch#383]
I tried to connect mailisearch from strapi.
But it doesn’t work… 😢 :
I click collection’s checkbox on strapi, but it doesn’t work…
I add plugin `strapi-plugin-meilisearch` and added plugins.js.

```
// plugins.js
module.exports = () => ({
    //...
    meilisearch: {
        config: {
            // Your meili host
            host: "http://mailisearch:7700/",
            // Your master key or private key
            apiKey: "your_master_key",
        }
    }
})
```
**Version**
strapi: v4.1.5  
node: v14.19.1  
docker: 20.10.13  
Mac: Big Sur 11.6.11 (Intel chip)  
mailisearch: 0.26.1  

```
version: '3'

services:
  strapi:
    build: .
    restart: unless-stopped
    container_name: strapi
    image: asigar_strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - NODE_ENV=development
    ports:
      - 1337:1337
    volumes:
      - node_modules:/opt/node_modules
      - postgres:/opt/postgres
      - ./:/opt
    depends_on:
      - postgres
      - mailisearch
    # command: /bin/sh -c "while :; do sleep 10; done"

  postgres:
    image: postgres:13-alpine
    container_name: strapi_v4_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./postgres:/var/lib/postgresql/data
  mailisearch:
    image: getmeili/meilisearch
    container_name: mailisearch
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: your_master_key
    volumes:
      - ./data/meilisearch/data.ms:/data.ms
    depends_on:
      - postgres
    ports:
      - 7700:7700

volumes:
  node_modules:
  postgres:
```

I saw logs, but error doesn’t…

```
mailisearch    | 
mailisearch    | 888b     d888          d8b 888 d8b                                            888
mailisearch    | 8888b   d8888          Y8P 888 Y8P                                            888
mailisearch    | 88888b.d88888              888                                                888
mailisearch    | 888Y88888P888  .d88b.  888 888 888 .d8888b   .d88b.   8888b.  888d888 .d8888b 88888b.
mailisearch    | 888 Y888P 888 d8P  Y8b 888 888 888 88K      d8P  Y8b     "88b 888P"  d88P"    888 "88b
mailisearch    | 888  Y8P  888 88888888 888 888 888 "Y8888b. 88888888 .d888888 888    888      888  888
mailisearch    | 888   "   888 Y8b.     888 888 888      X88 Y8b.     888  888 888    Y88b.    888  888
mailisearch    | 888       888  "Y8888  888 888 888  88888P'  "Y8888  "Y888888 888     "Y8888P 888  888
mailisearch    | 
mailisearch    | Database path:         "./data.ms"
mailisearch    | Server listening on:   "http://0.0.0.0:7700/"
mailisearch    | Environment:           "development"
mailisearch    | Commit SHA:            "unknown"
mailisearch    | Commit date:           "unknown"
mailisearch    | Package version:       "0.26.1"
mailisearch    | 
mailisearch    | Thank you for using Meilisearch!
mailisearch    | 
mailisearch    | We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://docs.meilisearch.com/learn/what_is_meilisearch/telemetry.html
mailisearch    | 
mailisearch    | Anonymous telemetry:   "Enabled"
mailisearch    | Instance UID:          "12639e69-3767-4753-aa90-3d064f20ff8e"
mailisearch    | 
mailisearch    | A Master Key has been set. Requests to Meilisearch won't be authorized unless you provide an authentication key.
mailisearch    | 
mailisearch    | Documentation:         https://docs.meilisearch.com/
mailisearch    | Source code:           https://github.com/meilisearch/meilisearch
mailisearch    | Contact:               https://docs.meilisearch.com/resources/contact.html
mailisearch    | 
mailisearch    | [2022-04-18T06:16:28Z INFO  actix_server::builder] Starting 6 workers
mailisearch    | [2022-04-18T06:16:28Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
mailisearch    | [2022-04-18T06:16:37Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes HTTP/1.1" 200 267 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.014339
mailisearch    | [2022-04-18T06:16:55Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes HTTP/1.1" 200 267 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.000972
mailisearch    | [2022-04-18T06:16:56Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes/help/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003770
mailisearch    | [2022-04-18T06:16:56Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes/user/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003350
mailisearch    | [2022-04-18T06:16:57Z INFO  actix_web::middleware::logger] 172.21.0.4 "POST /indexes/help/settings HTTP/1.1" 202 116 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.005267
mailisearch    | [2022-04-18T06:17:01Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes HTTP/1.1" 200 267 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004090
mailisearch    | [2022-04-18T06:17:04Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes HTTP/1.1" 200 267 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.000798
mailisearch    | [2022-04-18T06:17:04Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes/user/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.001185
mailisearch    | [2022-04-18T06:17:04Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes/help/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.001736
mailisearch    | [2022-04-18T06:17:05Z INFO  actix_web::middleware::logger] 172.21.0.4 "POST /indexes/help/settings HTTP/1.1" 202 116 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003957
mailisearch    | [2022-04-18T06:17:09Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes HTTP/1.1" 200 267 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002738
mailisearch    | [2022-04-18T06:17:14Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes HTTP/1.1" 200 267 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.000683
mailisearch    | [2022-04-18T06:17:14Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes/help/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004202
mailisearch    | [2022-04-18T06:17:14Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes/user/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002687
mailisearch    | [2022-04-18T06:18:34Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes HTTP/1.1" 200 267 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.000697
mailisearch    | [2022-04-18T06:18:34Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes/user/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003920
mailisearch    | [2022-04-18T06:18:34Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes/help/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004317
mailisearch    | [2022-04-18T06:18:59Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes HTTP/1.1" 200 267 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.000838
mailisearch    | [2022-04-18T06:18:59Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes/help/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003762
mailisearch    | [2022-04-18T06:18:59Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes/user/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003987
mailisearch    | [2022-04-18T06:19:02Z INFO  actix_web::middleware::logger] 172.21.0.4 "POST /indexes/help/settings HTTP/1.1" 202 116 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004586
mailisearch    | [2022-04-18T06:19:06Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes HTTP/1.1" 200 267 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.005141
mailisearch    | [2022-04-18T06:19:09Z INFO  actix_web::middleware::logger] 172.21.0.4 "POST /indexes/user/settings HTTP/1.1" 202 116 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004045
mailisearch    | [2022-04-18T06:19:13Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes HTTP/1.1" 200 267 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004039
mailisearch    | [2022-04-18T06:26:04Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes HTTP/1.1" 200 267 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.001503
mailisearch    | [2022-04-18T06:26:04Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes/help/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.006832
mailisearch    | [2022-04-18T06:26:04Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes/user/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008037
mailisearch    | [2022-04-18T06:26:05Z INFO  actix_web::middleware::logger] 172.21.0.4 "POST /indexes/help/settings HTTP/1.1" 202 116 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.005238
mailisearch    | [2022-04-18T06:26:09Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /indexes HTTP/1.1" 200 267 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004809

strapi         | Welcome back!
strapi         | To manage your project 🚀, go to the administration panel at:
strapi         | http://localhost:1337/admin
strapi         | 
strapi         | To access the server ⚡️, go to:
strapi         | http://localhost:1337/
strapi         | 
strapi         | [2022-04-18 06:26:04.123] http: GET /meilisearch/content-type/ (177 ms) 200
strapi         | [2022-04-18 06:26:05.573] info: File changed: /opt/data/meilisearch/data.ms/data.mdb
strapi         | [2022-04-18 06:26:05.575] info: The server is restarting
strapi         | 
strapi         | [2022-04-18 06:26:05.590] info: File changed: /opt/data/meilisearch/data.ms/indexes/908380e0-5989-471c-bdf9-e9f8dddc9420/data.mdb
```
