### ISSUE TITLE
Meilisearch refused /indexes connection

### ISSUE THREAD

**Issue by rortan134** [meilisearch/strapi-plugin-meilisearch#495]
**Description**

When using meilisearch with docker, i'm currently getting this error after opening the Meilisearch tab in the strapi dashboard

```
strapi_1 | [2022-08-27 13:50:01.503] error: meilisearch: request to http://localhost:7700/indexes failed, reason: connect ECONNREFUSED 127.0.0.1:7700
```

Opening the same tab in my browser with no master key set returns the correct info.
Error happens with or without master key set.

**Expected behavior**

Strapi request goes through.

**Current behavior**

Strapi request to meilisearch /indexes failed to connect/respond.

Dockerfile
```
FROM node:16.15.0 AS build

WORKDIR /app

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install --production --network-timeout 600000

COPY . ./

ENV NODE_ENV production

RUN yarn build

# strapi dashboard 
EXPOSE 1337
# meilisearch api
EXPOSE 7700

CMD ["yarn", "run", "develop"]
```
Docker-compose
```
version: "3"
services:
  strapi:
    build: .
    image: strapi/strapi
    ports:
      - "1337:1337"
    depends_on:
      - meilisearch
    tty: true
  meilisearch:
    image: getmeili/meilisearch
    command: meilisearch --master-key="master_key"
    volumes:
      - ../meilisearch/data.ms:/data.ms
    ports:
      - "7700:7700"
```
Settings
![image](https://user-images.githubusercontent.com/37253958/187033393-14d62c8a-0d10-41b7-a53e-dda7bef50458.png)

**Environment**

- OS: Windows
- Meilisearch version: v0.28.1
- strapi-plugin-meilisearch version: ^0.7.1
- Browser: Chrome
- Strapi version: 4.3.4
